# Probabilities
GRASS_BURN_PROBABILTY = 1.0

FIRE_SPREAD_PROBABILITY = 0.9
FIRE_DISSAPATE_PROBABILTY = 0.2

STEAM_SPREAD_PROBABILTY = 0.8
STEAM_DISSAPATE_PROBABILTY = 0.5

# Frames that dissapatable entities linger
STEAM_DISSAPATE_N_FRAMES = 3
NECROTIC_SOIL_DISSIPATE_N_FRAMES = 5

# Healing amounts
HEALTH_POTION_HEAL_AMOUNT = 25

# Stats increasing items
HEALTH_POTION_HP_INCREASE_AMOUNT = 10
POWER_POTION_INCREASE_AMOUNT = 1

# Base damage amounts
BURN_BASE_DAMAGE = 5
SCALD_BASE_DAMAGE = 5
FREEZE_BASE_DAMAGE = 5
NECROTIC_SOIL_BASE_DAMAGE = 2
THROWING_KNIFE_BASE_DAMAGE = 5
MAGIC_MISSILE_BASE_DAMAGE = 5
FIREBLAST_SCROLL_BASE_DAMAGE = 5
WATERBLAST_SCROLL_BASE_DAMAGE = 5

# Damage scaling amounts
THROWN_WEAPON_DAMAGE_FACTOR = 10

# Spell ranges
MAGIC_MISSILE_RANGE = 10
FIREBLAST_SCROLL_RADIUS = 4
WATERBLAST_SCROLL_RADIUS = 4

# Consumable and rechargeable configuration
STAFF_RECHARGE_TIME = 1 #200
STAFF_BASE_USES = 3
THROWING_KNIFE_BASE_USES = 5

# Time period for effects that wear off over time
PLAYER_CONFUSED_DURATION = 10
ENEMY_CONFUSED_DURATION = 10
ENEMY_FROZEN_DURATION = 10

# Spell targeting
MAGIC_MISSILE_N_TARGETS = 3

# Boat blast radii and damage
FIREBLOAT_BLAST_RADIUS = 2
FIREBLOAT_BLAST_DAMAGE = 6

WATERBLOAT_BLAST_RADIUS = 2
WATERBLOAT_BLAST_DAMAGE = 6

# Weapon configuration
RAIPIER_RANGE = 6
