TERRAIN_SCHEDULES = [
    {
        'upward_stairs': False,
        'min_torches': 0,
        'max_torches': 0,
        'min_pools': 0,
        'max_pools': 1,
        'pool_room_proportion': 0.7,
        'min_rivers': 0,
        'max_rivers': 0,
        'min_grass': 2,
        'max_grass': 6,
        'grass_room_proportion': 2.0,
        'min_shrubs': 0,
        'max_shrubs': 0,
        'shrubs_room_proportion': 0.0,
        'min_ice': 0,
        'max_ice': 0,
        'ice_room_proportion': 0.0,
    },
    {
        'min_torches': 3,
        'max_torches': 10,
        'min_pools': 2,
        'max_pools': 4,
        'pool_room_proportion': 0.7,
        'min_rivers': 0,
        'max_rivers': 1,
        'min_grass': 2,
        'max_grass': 6,
        'grass_room_proportion': 2.0,
        'min_shrubs': 0,
        'max_shrubs': 0,
        'shrubs_room_proportion': 0.0,
        'min_ice': 0,
        'max_ice': 0,
        'ice_room_proportion': 0.0,
    },
    {
        'min_torches': 3,
        'max_torches': 10,
        'min_pools': 3,
        'max_pools': 10,
        'pool_room_proportion': 0.7,
        'min_rivers': 0,
        'max_rivers': 3,
        'min_grass': 2,
        'max_grass': 6,
        'grass_room_proportion': 2.0,
        'min_shrubs': 0,
        'max_shrubs': 1,
        'shrubs_room_proportion': 0.7,
        'min_ice': 0,
        'max_ice': 1,
        'ice_room_proportion': 0.7,
    },
]
