TERRAIN_SCHEDULES = [
    {
        'upward_stairs': False,
        'min_pools': 0,
        'max_pools': 1,
        'pool_room_proportion': 0.7,
        'min_rivers': 0,
        'max_rivers': 0,
        'min_grass': 1,
        'max_grass': 2,
        'grass_room_proportion': 2.0,
        'min_shrubs': 0,
        'max_shrubs': 0,
        'shrubs_room_proportion': 0.0,
        'min_ice': 0,
        'max_ice': 0,
        'ice_room_proportion': 0.0,
    },
    {
        'min_pools': 0,
        'max_pools': 2,
        'pool_room_proportion': 0.7,
        'min_rivers': 0,
        'max_rivers': 1,
        'min_grass': 1,
        'max_grass': 2,
        'grass_room_proportion': 2.0,
        'min_shrubs': 0,
        'max_shrubs': 0,
        'shrubs_room_proportion': 0.0,
        'min_ice': 0,
        'max_ice': 0,
        'ice_room_proportion': 0.0,
    },
    {
        'min_pools': 0,
        'max_pools': 2,
        'pool_room_proportion': 0.7,
        'min_rivers': 0,
        'max_rivers': 1,
        'min_grass': 1,
        'max_grass': 2,
        'grass_room_proportion': 2.0,
        'min_shrubs': 0,
        'max_shrubs': 0,
        'shrubs_room_proportion': 0.0,
        'min_ice': 0,
        'max_ice': 0,
        'ice_room_proportion': 0.0,
    },
]
